Update CONTRIBUTING.md
callysto/curriculum-notebooks pull request #220
Opened 2021-07-23 23:12 UTC by ZachAttacksProblems

Update to indicate notebooks should be cleared off outputs before submitting a PR.

2021-07-24 00:16 UTC, byrcyb commented
Dang, the second I wrote my previous comment on PR#219 I knew I should have double checked our contributing guide.

2021-07-24 00:19 UTC, byrcyb requested changes
Thanks for adding this in. I could have sworn it was in this doc at some point, but, regardless, I'm happy you did.

2021-07-24 00:19 UTC, byrcyb commented on CONTRIBUTING.md
> +We consider it a best practice to clear all cell outputs before commiting. This can be done with 'Kernel > Restar & Clear Output' (or 'Edit > Clear All Outputs' in JupyterLab) from the top menu bar.
one small typo "Restar" -> "Restart"

2021-07-26 16:16 UTC, ZachAttacksProblems commented on CONTRIBUTING.md
> +We consider it a best practice to clear all cell outputs before commiting. This can be done with 'Kernel > Restar & Clear Output' (or 'Edit > Clear All Outputs' in JupyterLab) from the top menu bar.
Fixed typo.

2021-07-29 16:05 UTC, byrcyb approved these changes
Thanks for fixing the typo and updating the doc.

2021-07-29 16:05 UTC, byrcyb commented on CONTRIBUTING.md
> +We consider it a best practice to clear all cell outputs before commiting. This can be done with 'Kernel > Restar & Clear Output' (or 'Edit > Clear All Outputs' in JupyterLab) from the top menu bar.
Awesome, thanks!

2021-07-29 16:06 UTC, merged